version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: funnelalchemy
      POSTGRES_PASSWORD: funnelalchemy
      POSTGRES_DB: funnelalchemy
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: test-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
